# Adjust ROBOTRACONTEUR_VERSION_SEMVER for Python version format

# if(ROBOTRACONTEUR_VERSION_SEMVER MATCHES "--dev") string(REPLACE "--dev" ".dev" ROBOTRACONTEUR_VERSION_PY
# "${ROBOTRACONTEUR_VERSION_SEMVER}") else()
string(REPLACE "-" "" ROBOTRACONTEUR_VERSION_PY "${ROBOTRACONTEUR_VERSION_SEMVER}")
# endif()

# Add .post1 for this patch
set(ROBOTRACONTEUR_VERSION_PY "${ROBOTRACONTEUR_VERSION_PY}.post1")

message("RobotRaconteur Python Package Version ${ROBOTRACONTEUR_VERSION_PY}")
