name: Build Python Version

on: 
  workflow_dispatch:
    inputs:
      ref:
        description: 'git ref to build'
        required: true
      python_version:
        description: 'Python version'
        required: true

jobs:
  build-win:
    runs-on: windows-2016
    strategy:
      matrix:
        arch: [x64,x86]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: '${{ github.event.inputs.ref }}'
        repository: robotraconteur/robotraconteur
    - uses: actions/setup-python@v2
      with:
        python-version: '${{ github.event.inputs.python_version }}'
        architecture: ${{ matrix.arch }}
    - name: pip3
      run: |
        python -m pip install numpy setuptools wheel
    - name: env python3
      run: echo  ("PYTHON3_EXE=" + (Get-Command Python.exe).Path) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - name: choco
      run: |
        choco install swig -r
    - uses: haya14busa/action-cond@v1
      id: cmake_arch
      with:
        cond: ${{ matrix.arch == 'x86' }}
        if_true: "Win32"
        if_false: "x64"
    - name: configure
      run: >
        cd .. &&
        md -Force build2 && cd build2 &&
        cmake -G "Visual Studio 15 2017" -A ${{ steps.cmake_arch.outputs.value }} 
        -DBoost_USE_STATIC_LIBS=ON
        -DBUILD_PYTHON3=ON -DBUILD_PYTHON3_WHEEL=ON 
        -DBOOST_ROOT="${env:BOOST_ROOT_1_72_0}"
        -DPYTHON3_EXECUTABLE="${{ env.PYTHON3_EXE }}"
        ../robotraconteur
    - name: build
      run: |
        cd ../build2
        cmake --build . --config Release -j 4
    - name: test
      run: |
        cd ../build2
        ctest . -C Release --output-on-failure
    - name: move out
      run: |
        mv ../build2/out .
    - name: archive out
      uses: actions/upload-artifact@v2
      with:
        name: 'out-win-${{ matrix.arch }}'
        path: out/*

  build-osx:

    runs-on: macos-10.15
    env:
      LIBRARY_PATH: /usr/local/opt/icu4c/lib
    steps:
    - uses: actions/checkout@v2
      with:
        ref: '${{ github.event.inputs.ref }}'
        repository: robotraconteur/robotraconteur
    - name: brew
      run: |
        brew install swig boost openssl
    - uses: actions/setup-python@v2
      with:
        python-version: '${{ github.event.inputs.python_version }}'
        architecture: x64
    - name: pip3
      run: |
        python -m pip install numpy setuptools wheel
    - name: env python3
      run: echo "PYTHON3_EXE=${{ env.pythonLocation }}/bin/python" >> $GITHUB_ENV
    - name: configure
      run: >
        cd .. &&
        mkdir build2 && cd build2 &&
        cmake -G "Xcode" -DBUILD_GEN=ON  -DBUILD_PYTHON3=ON -DBUILD_PYTHON3_WHEEL=ON 
        -DBoost_USE_STATIC_LIBS=ON -DCMAKE_BUILD_TYPE=Release        
        -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl
        -DOPENSSL_USE_STATIC_LIBS=ON
        -DPYTHON3_EXECUTABLE="${{ env.PYTHON3_EXE }}"
        ../robotraconteur
    - name: build
      run: |        
        cd ../build2
        cmake --build . --config Release -j 4
    - name: test
      run: |
        cd ../build2
        ctest . -C Release --output-on-failure
    - name: move out
      run: |
        mv ../build2/out .
    - name: archive out
      uses: actions/upload-artifact@v2
      with:
        name: 'out-osx'
        path: out/*
    
      