name: Build Matlab Toolbox

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name of draft release'
        required: true

jobs:
  build-matlab-toolbox:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
      with:
        path: robotraconteur
    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v1
      with:
        release: R2020a
    - name: pip
      run: python3 -m pip install pygithub setuptools
    - name: build matlab toolbox
      env:
        BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
      run: python3 robotraconteur/packaging/scripts/build_matlab_toolbox.py