name: distfiles_test

on:
  push:
  workflow_dispatch:

jobs:
  distfiles-test-win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - arch: x64
            wheel_arch: win_amd64
          - arch: x86
            wheel_arch: win32
    steps:
      - uses: actions/checkout@v2
        with:
          path: robotraconteur
      # - name: Download distfiles
      #   uses: actions/download-artifact@v2
      #   with:
      #     path: artifacts/distfiles
      #     name: distfiles
      - name: Download distfiles
        uses: dawidd6/action-download-artifact@v2
        with:
          path: artifacts/distfiles
          name: distfiles
          run_id: 6952928340
      - name: tree
        run: tree /F artifacts
        shell: cmd
      - name: .net test
        uses: ./robotraconteur/test/dist/net/action/win
        with:
          arch: ${{ matrix.config.arch }}
      - uses: ./robotraconteur/test/dist/python/action/win
        with:
          python_version: 3.7
          arch: ${{ matrix.config.arch }}
          wheel_filename: RobotRaconteur-*-cp37-cp37m-${{ matrix.config.wheel_arch }}.whl
      - uses: ./robotraconteur/test/dist/python/action/win
        with:
          python_version: 3.8
          arch: ${{ matrix.config.arch }}
          wheel_filename: RobotRaconteur-*-cp38-cp38-${{ matrix.config.wheel_arch }}.whl
      - uses: ./robotraconteur/test/dist/python/action/win
        with:
          python_version: 3.9
          arch: ${{ matrix.config.arch }}
          wheel_filename: RobotRaconteur-*-cp39-cp39-${{ matrix.config.wheel_arch }}.whl
      - uses: ./robotraconteur/test/dist/python/action/win
        with:
          python_version: "3.10"
          arch: ${{ matrix.config.arch }}
          wheel_filename: RobotRaconteur-*-cp310-cp310-${{ matrix.config.wheel_arch }}.whl
      - uses: ./robotraconteur/test/dist/python/action/win
        with:
          python_version: "3.11"
          arch: ${{ matrix.config.arch }}
          wheel_filename: RobotRaconteur-*-cp311-cp311-${{ matrix.config.wheel_arch }}.whl
  distfiles-test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: robotraconteur
      # - name: Download distfiles
      #   uses: actions/download-artifact@v2
      #   with:
      #     path: artifacts/distfiles
      #     name: distfiles
      - name: Download distfiles
        uses: dawidd6/action-download-artifact@v2
        with:
          path: artifacts/distfiles
          name: distfiles
          run_id: 6952928340
      - uses: ./robotraconteur/test/dist/python/action/linux
        with:
          python_version: 3.7
          wheel_filename: RobotRaconteur-*-cp37-cp37m-manylinux*x86_64.whl
      - uses: ./robotraconteur/test/dist/python/action/linux
        with:
          python_version: 3.8
          wheel_filename: RobotRaconteur-*-cp38-cp38-manylinux*x86_64.whl
      - uses: ./robotraconteur/test/dist/python/action/linux
        with:
          python_version: 3.9
          wheel_filename: RobotRaconteur-*-cp39-cp39-manylinux*x86_64.whl
      - uses: ./robotraconteur/test/dist/python/action/linux
        with:
          python_version: "3.10"
          wheel_filename: RobotRaconteur-*-cp310-cp310-manylinux*x86_64.whl
      - uses: ./robotraconteur/test/dist/python/action/linux
        with:
          python_version: "3.11"
          wheel_filename: RobotRaconteur-*-cp311-cp311-manylinux*x86_64.whl
  distfiles-test-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: robotraconteur
      # - name: Download distfiles
      #   uses: actions/download-artifact@v2
      #   with:
      #     path: artifacts/distfiles
      #     name: distfiles
      - name: Download distfiles
        uses: dawidd6/action-download-artifact@v2
        with:
          path: artifacts/distfiles
          name: distfiles
          run_id: 6952928340
      - uses: ./robotraconteur/test/dist/python/action/osx
        with:
          python_version: 3.7
          wheel_filename: RobotRaconteur-*-cp37-cp37m-macosx*x86_64.whl
      - uses: ./robotraconteur/test/dist/python/action/osx
        with:
          python_version: 3.8
          wheel_filename: RobotRaconteur-*-cp38-cp38-macosx*x86_64.whl
      - uses: ./robotraconteur/test/dist/python/action/osx
        with:
          python_version: 3.9
          wheel_filename: RobotRaconteur-*-cp39-cp39-macosx*x86_64.whl
      - uses: ./robotraconteur/test/dist/python/action/osx
        with:
          python_version: "3.10"
          wheel_filename: RobotRaconteur-*-cp310-cp310-macosx*x86_64.whl
      - uses: ./robotraconteur/test/dist/python/action/osx
        with:
          python_version: "3.11"
          wheel_filename: RobotRaconteur-*-cp311-cp311-macosx*x86_64.whl